name: Test Workflow
on:
  pull_request_target:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "¡El workflow se ejecutó! Label: ${{ github.event.label.name }}"